CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(191) UNIQUE NOT NULL,
  pass_hash VARCHAR(255) NOT NULL,
  role VARCHAR(60) NOT NULL DEFAULT 'Staff',
  color VARCHAR(20) DEFAULT '#BA7517',
  avatar_url TEXT,
  permissions JSON NOT NULL,
  linked_google TINYINT(1) DEFAULT 0,
  linked_facebook TINYINT(1) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS inventory (
  id VARCHAR(36) PRIMARY KEY,
  model VARCHAR(191) NOT NULL,
  config VARCHAR(100) DEFAULT '',
  brand VARCHAR(80) NOT NULL,
  type VARCHAR(40) NOT NULL DEFAULT 'Regular',
  color VARCHAR(80) DEFAULT '',
  house VARCHAR(120) DEFAULT '',
  source VARCHAR(255) DEFAULT '',
  price DECIMAL(10,2) DEFAULT 0,
  start_stock INT NOT NULL DEFAULT 0,
  stock_in INT NOT NULL DEFAULT 0,
  stock_out INT NOT NULL DEFAULT 0,
  description TEXT,
  note TEXT,
  image_url TEXT,
  imeis JSON DEFAULT NULL,
  variations JSON DEFAULT NULL,
  deleted_at DATETIME DEFAULT NULL,
  deleted_by VARCHAR(36) DEFAULT NULL,
  created_by VARCHAR(36) DEFAULT NULL,
  date_added DATE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_brand (brand), INDEX idx_type (type), INDEX idx_deleted (deleted_at), INDEX idx_model (model)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS history (
  id VARCHAR(36) PRIMARY KEY,
  inv_id VARCHAR(36) NOT NULL,
  model VARCHAR(191) NOT NULL,
  config VARCHAR(100) DEFAULT '',
  type VARCHAR(60),
  action VARCHAR(10) NOT NULL,
  qty INT NOT NULL,
  note TEXT,
  created_by VARCHAR(36),
  date DATE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_inv (inv_id), INDEX idx_date (date),
  CONSTRAINT fk_history_inventory FOREIGN KEY (inv_id) REFERENCES inventory(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sessions (
  token VARCHAR(64) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wa_chats (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  name VARCHAR(191) NOT NULL,
  type VARCHAR(20) DEFAULT 'contact',
  color VARCHAR(20),
  status_txt VARCHAR(191) DEFAULT '',
  messages JSON DEFAULT NULL,
  unread INT DEFAULT 0,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
